import {AppError,encrypt,decrypt} from './core.js';
export class Meli{
 constructor(repo,env,fetcher=fetch){this.repo=repo;this.env=env;this.fetcher=fetcher;}
 async exchange(fields,c=this.repo.db){const e=this.env;if(!e.MELI_CLIENT_ID||!e.MELI_CLIENT_SECRET)throw new AppError('Configure as credenciais do aplicativo Mercado Livre.',503);let r,b;try{r=await this.fetcher('https://api.mercadolibre.com/oauth/token',{method:'POST',body:new URLSearchParams({client_id:e.MELI_CLIENT_ID,client_secret:e.MELI_CLIENT_SECRET,...fields}),signal:AbortSignal.timeout(10000)});b=await r.json();}catch{throw new AppError('Falha na conexão OAuth. Refaça a autorização.',502);}if(!r.ok||!b.access_token||!b.refresh_token||!Number.isFinite(b.expires_in))throw new AppError(`Mercado Livre recusou a autorização (HTTP ${r.status}). Confira credenciais e redirect URI.`,502);const tokens={access_token:b.access_token,refresh_token:b.refresh_token,expires_at:Date.now()+b.expires_in*1000};await c.query("INSERT INTO pc_tokens(id,value) VALUES('meli',$1) ON CONFLICT(id) DO UPDATE SET value=EXCLUDED.value",[encrypt(tokens,e.TOKEN_ENCRYPTION_KEY)]);return tokens.access_token;}
 async token(force=false){return this.repo.tx(async c=>{await c.query("INSERT INTO pc_tokens(id,value) VALUES('meli','') ON CONFLICT DO NOTHING");const {rows:[row]}=await c.query("SELECT value FROM pc_tokens WHERE id='meli' FOR UPDATE");if(!row.value)throw new AppError('Conecte sua conta do Mercado Livre no painel.',409);const tokens=decrypt(row.value,this.env.TOKEN_ENCRYPTION_KEY);if(force||tokens.expires_at<=Date.now())return this.exchange({grant_type:'refresh_token',refresh_token:tokens.refresh_token},c);return tokens.access_token;});}
 async get(path,params={},retry=true){const token=await this.token();let r,b;try{r=await this.fetcher('https://api.mercadolibre.com'+path+'?'+new URLSearchParams(params),{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(8000)});b=await r.json();}catch{throw new AppError('Falha de conexão com o Mercado Livre.',502);}if(r.status===401&&retry){await this.token(true);return this.get(path,params,false);}if(r.status===403){const resource=path==='/products/search'?'/products/search':/^\/products\/MLB\d+\/items$/.test(path)?'/products/{id}/items':'recurso solicitado';const known=['PA_UNAUTHORIZED_RESULT_FROM_POLICIES','forbidden','access_denied','insufficient_scope'];const code=[b?.code,b?.error].find(v=>known.includes(v));throw new AppError(`Mercado Livre recusou GET ${resource} (403)${code?': '+code:''}. A autorização da conta não garante acesso a este recurso.`,403);}if(r.status===429)throw new AppError('Limite de consultas do Mercado Livre. Tente mais tarde.',429);if(!r.ok)throw new AppError(`Falha na API do Mercado Livre (HTTP ${r.status}).`,502);return b;}
 async collect(query){if(typeof query!=='string'||query.trim().length<3||query.length>100)throw new AppError('Digite uma busca entre 3 e 100 caracteres.');const data=await this.get('/products/search',{site_id:'MLB',status:'active',q:query.trim(),limit:3});if(!Array.isArray(data.results))throw new AppError('Resposta de catálogo inválida.',502);const offers=[];const min=Number(this.env.MELI_MIN_DISCOUNT??10),max=Number(this.env.MELI_MAX_PRICE??0);if(!Number.isFinite(min)||min<0||min>100||!Number.isFinite(max)||max<0)throw new AppError('Filtros de preço/desconto inválidos.',503);
 for(const p of data.results.slice(0,3)){if(!/^MLB\d+$/.test(p.id)||p.status!=='active'||!p.name)continue;const params={limit:3};if(min)params.discount=`${min}-100`;if(max)params.price=`0-${max}`;const listing=await this.get(`/products/${p.id}/items`,params);if(!Array.isArray(listing.results))throw new AppError('Resposta de publicações inválida.',502);for(const item of listing.results.slice(0,3)){if(!/^MLB\d+$/.test(item.item_id)||item.currency_id!=='BRL'||!Number.isFinite(item.price)||item.price<=0||(max&&item.price>max))continue;offers.push({external_id:item.item_id,titulo:p.name,preco:new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(item.price),loja:'Mercado Livre',link_original:`https://produto.mercadolivre.com.br/MLB-${item.item_id.slice(3)}`,link_afiliado:'',fonte:'mercado_livre',observacao:'Confira variante, vendedor e disponibilidade. Gere seu link na plataforma de afiliados antes de aprovar.'});}}
 return offers;}
}
