import {useEffect,useState} from 'react';
import {ShoppingBag,RefreshCw,LogOut,ExternalLink,Check,Search,ShieldCheck} from 'lucide-react';

const states={pendente:'Para revisar',aprovado:'Aprovada',publicado:'Publicada',enviando:'Aguardando confirmação',incerto:'Conferir no canal',erro:'Erro no envio',descartado:'Descartada'};
function safeLink(value){try{return ['http:','https:'].includes(new URL(value).protocol)?value:null;}catch{return null;}}
const button='px-4 py-2 rounded-xl border border-gray-200 text-sm font-medium disabled:opacity-50 hover:bg-gray-50';
export default function PainelOfertas(){
 const [session,setSession]=useState(null),[password,setPassword]=useState(''),[offers,setOffers]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[filter,setFilter]=useState('todas'),[search,setSearch]=useState('tênis corrida'),[source,setSource]=useState('mercado_livre');
 async function api(op,body,csrf=session?.csrf){const r=await fetch('/api?op='+op,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf||''}:{},body:body?JSON.stringify(body):undefined});let data;try{data=await r.json();}catch{throw Error('A API não respondeu. Confira a configuração da hospedagem.');}if(!r.ok){if(r.status===401&&op!=='login')setSession(null);throw Error(data.erro||'Não foi possível concluir a operação.');}return data;}
 async function reload(){setOffers(await api('offers'));}
 async function action(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{let active=true;(async()=>{try{const s=await api('session');if(!active)return;setSession(s.autenticado?s:null);if(s.autenticado){const o=await api('offers');if(active)setOffers(o);}}catch(e){if(active)setError(e.message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 async function login(e){e.preventDefault();await action(async()=>{const s=await api('login',{password});setPassword('');setSession(s);setOffers(await api('offers',undefined,s.csrf));});}
 if(loading)return <div className="min-h-screen grid place-items-center text-emerald-900">Abrindo painel…</div>;
 if(!session)return <div className="min-h-screen flex items-center justify-center p-6 bg-[#0f2e1f]"><main className="w-full max-w-sm"><ShoppingBag className="text-emerald-300 mx-auto mb-4" size={42}/><h1 className="text-3xl text-center font-bold text-white">Passada Certa</h1><p className="text-center text-emerald-200/70 mt-2 mb-8">Seu painel de ofertas</p><form onSubmit={login} className="bg-white/5 rounded-2xl p-6 border border-white/10"><label htmlFor="password" className="block text-emerald-100 mb-2">Senha de acesso</label><input id="password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className="w-full p-3 rounded-xl bg-white/10 text-white border border-white/20"/><button disabled={busy} className="w-full mt-4 py-3 rounded-xl bg-emerald-700 text-white font-medium">{busy?'Entrando…':'Entrar'}</button>{error&&<p role="alert" className="text-rose-200 text-sm mt-4">{error}</p>}</form><p className="text-center text-xs text-emerald-200/50 mt-6">Acesso restrito à equipe do canal</p></main></div>;
 const visible=offers.filter(o=>filter==='todas'||o.estado===filter);
 return <div className="min-h-screen bg-[#f7f9f8] text-gray-900"><header className="border-b bg-white"><div className="max-w-4xl mx-auto px-4 py-5 flex justify-between items-center"><div className="flex gap-3 items-center"><ShoppingBag className="text-emerald-800"/><div><h1 className="font-bold text-xl">Passada Certa</h1><p className="text-xs text-gray-500">Ofertas para revisar e compartilhar</p></div></div><div className="flex gap-2"><button className={button} disabled={busy} onClick={()=>action(reload)} aria-label="Atualizar lista"><RefreshCw size={17}/></button><button className={button} disabled={busy} onClick={()=>action(async()=>{await api('logout',{});setSession(null);setOffers([]);})} aria-label="Sair"><LogOut size={17}/></button></div></div></header>
 <main className="max-w-4xl mx-auto px-4 py-6"><div className="grid grid-cols-3 gap-3 mb-6">{[['Para revisar','pendente'],['Aprovadas','aprovado'],['Publicadas','publicado']].map(([label,state])=><div key={state} className="bg-white border rounded-2xl p-4"><strong className="text-2xl text-emerald-900">{offers.filter(o=>o.estado===state).length}</strong><p className="text-xs text-gray-500">{label}</p></div>)}</div>
 <section className="rounded-2xl border bg-white p-5 mb-5"><h2 className="font-semibold mb-3">Encontrar novas ofertas</h2><div className="flex flex-wrap gap-2"><select aria-label="Fonte de ofertas" value={source} onChange={e=>setSource(e.target.value)} className="p-2 border rounded-xl"><option value="mercado_livre">Mercado Livre</option><option value="promobit">Promobit</option></select>{source==='mercado_livre'&&<input aria-label="Busca de produtos" value={search} onChange={e=>setSearch(e.target.value)} maxLength={100} className="flex-1 min-w-40 border rounded-xl px-3 py-2"/>}<button className={button} disabled={busy} onClick={()=>action(async()=>{const r=await api('collect',{fonte:source,busca:search});await reload();setNotice(`${r.adicionadas} novas ofertas adicionadas para revisão.`);})}><Search className="inline mr-1" size={15}/>Buscar ofertas</button></div><div className="flex flex-wrap gap-3 mt-4"><button className="text-sm text-emerald-800 underline disabled:opacity-50" disabled={busy} onClick={()=>action(async()=>{const r=await api('meli-auth',{});const url=new URL(r.url);if(url.origin!=='https://auth.mercadolivre.com.br')throw Error('URL de autorização inválida.');window.location.assign(url.href);})}>Conectar Mercado Livre</button><button className="text-sm text-gray-600 underline disabled:opacity-50" disabled={busy} onClick={()=>action(async()=>{const r=await api('import',{});await reload();setNotice(`${r.adicionadas} ofertas importadas. Publicações anteriores foram preservadas.`);})}>Importar fila antiga</button></div><p className="text-xs text-gray-500 mt-3">A busca adiciona produtos para revisão. Confira preço, variante e vendedor antes de aprovar.</p></section>
 <div className="flex flex-wrap items-center gap-3 mb-5 justify-between"><select aria-label="Filtrar ofertas" value={filter} onChange={e=>setFilter(e.target.value)} className="border rounded-xl px-3 py-2 bg-white"><option value="todas">Todas as ofertas</option>{Object.entries(states).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><button disabled={busy||!offers.some(o=>o.estado==='aprovado')} className="px-4 py-2 rounded-xl bg-emerald-800 text-white text-sm disabled:opacity-40" onClick={()=>action(async()=>{if(!window.confirm('Enviar uma oferta aprovada ao canal do Telegram agora?'))return;const r=await api('publish',{});await reload();setNotice(r.processadas?`Resultado do envio: ${states[r.estado]||r.estado}.`:'Nenhuma oferta aprovada para enviar.');})}>Publicar próxima aprovada</button></div>
 {error&&<p role="alert" className="bg-rose-50 border border-rose-200 text-rose-800 rounded-xl p-4 mb-4">{error}</p>}{notice&&<p role="status" className="bg-emerald-50 border border-emerald-200 text-emerald-900 rounded-xl p-4 mb-4">{notice}</p>}
 {!visible.length&&<div className="py-14 text-center text-gray-500">Nenhuma oferta nesta seleção.</div>}
 <div className="space-y-4">{visible.map(o=><Offer key={o.id+':'+o.version} offer={o} busy={busy} save={changes=>action(async()=>{await api('edit',{id:o.id,version:o.version,...changes});await reload();setNotice('Oferta atualizada.');})} reconcile={published=>action(async()=>{if(!window.confirm(published?'Você encontrou esta publicação no canal?':'Você conferiu o canal e tem certeza de que esta oferta não foi enviada?'))return;await api('reconcile',{id:o.id,publicado:published,conferido_no_canal:true});await reload();})}/>)}</div>
 <footer className="text-xs text-gray-500 mt-8 pb-6 flex gap-2"><ShieldCheck size={16}/>Somente ofertas aprovadas com link de afiliado podem ser enviadas. Em caso de envio incerto, confira o canal antes de tentar novamente.</footer></main></div>;
}
function Offer({offer:o,busy,save,reconcile}){const [title,setTitle]=useState(o.titulo),[price,setPrice]=useState(o.preco),[link,setLink]=useState(o.link_afiliado||'');const locked=['publicado','incerto','enviando'].includes(o.estado);return <article className="bg-white border border-gray-200 rounded-2xl p-5"><div className="flex justify-between gap-3 text-xs mb-4"><span className="text-gray-500">{o.fonte} · {o.loja}</span><span className="bg-emerald-50 text-emerald-800 px-2 py-1 rounded-full">{states[o.estado]}</span></div><div className="grid sm:grid-cols-[2fr_1fr] gap-3"><label className="text-xs text-gray-500">Título<input value={title} disabled={locked||busy} onChange={e=>setTitle(e.target.value)} className="block w-full mt-1 p-2 border rounded-lg text-gray-900"/></label><label className="text-xs text-gray-500">Preço / benefício<input value={price} disabled={locked||busy} onChange={e=>setPrice(e.target.value)} className="block w-full mt-1 p-2 border rounded-lg text-gray-900"/></label></div>{safeLink(o.link_original)&&<a className="text-xs text-emerald-800 inline-flex gap-1 items-center my-3" href={o.link_original} target="_blank" rel="noopener noreferrer"><ExternalLink size={13}/>Conferir produto</a>}{o.observacao&&<p className="text-xs text-gray-500 mb-3">{o.observacao}</p>}<label className="text-xs text-gray-500">Seu link de afiliado<input value={link} disabled={locked||busy} onChange={e=>setLink(e.target.value)} placeholder="https://…" className="block w-full mt-1 p-2 border rounded-lg text-gray-900"/></label>{o.erro&&<p className="text-sm text-rose-700 mt-3">{o.erro}</p>}<div className="flex flex-wrap gap-2 mt-4">{!locked&&<><button className={button} disabled={busy} onClick={()=>save({titulo:title,preco:price,link_afiliado:link,action:'salvar'})}>Salvar rascunho</button><button className={button+' text-emerald-800'} disabled={busy} onClick={()=>save({titulo:title,preco:price,link_afiliado:link,action:'aprovar'})}><Check size={15} className="inline mr-1"/>Aprovar</button><button className={button+' text-gray-500'} disabled={busy} onClick={()=>save({action:'descartar'})}>Descartar</button></>}{['incerto','enviando'].includes(o.estado)&&<><p className="w-full text-xs text-gray-500">Aguarde 5 minutos após a tentativa e confira o canal.</p><button className={button} disabled={busy} onClick={()=>reconcile(true)}>Já está no canal</button><button className={button} disabled={busy} onClick={()=>reconcile(false)}>Não foi enviada</button></>}</div></article>;}
